version: '3.8'

services:
  app:
    image: bloglist-frontend
    build: ./bloglist-frontend/.
    ports:
      - 3000:3000
    container_name: bloglist-frontend

  server:
    image: bloglist-backend
    build: ./bloglist-backend/.
    ports:
      - 3003:3003
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: bloglist-backend
  
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./bloglist-backend/mongo_data:/data/db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data: